import { defineVars } from "@stylexjs/stylex";

export const colorVariable = defineVars({
  mainBackground: "var(--bg-base)",
  subBackground: "var(--bg-surface)",
  green: "var(--color-green)",
  gold: "var(--color-gold)",
  blue: "var(--color-blue)",
  red: "var(--color-red)",
  purple: "var(--color-purple)",
  orange: "var(--color-orange)",
  pink: "var(--color-pink)",
  brown: "var(--color-brown)",
  gray: "var(--color-gray)",
  black: "var(--color-black)",
  white: "var(--color-white)",
  transparent: "var(--color-transparent)",
  fontBase: "var(--text-base)",
  fontMuted: "var(--text-muted)",
});

export const sizeVariable = defineVars({
  fullWidth: "100%",
  fullHeight: "100%",
  headerHeight: "50px",
  size0: "0px",
  size1: "1px",
  size2: "2px",
  size4: "4px",
  size8: "8px",
  size12: "12px",
  size16: "16px",
  size20: "20px",
  size24: "24px",
  size28: "28px",
  size32: "32px",
  size36: "36px",
  size50: "50px",
  size60: "60px",
  size70: "70px",
  size80: "80px",
  size90: "90px",
  size100: "100px",
});
